import { Rule, SchematicContext, Tree, chain, noop } from '@angular-devkit/schematics'

interface Schema {
  project?: string
}

/** The target application, as read from angular.json. */
interface TargetProject {
  name: string
  /** Directory served at the site root (the app assets folder). */
  publicDir: string
  /** `architect` (Angular CLI) or `targets` (Nx angular.json flavor). */
  targetsKey: 'architect' | 'targets'
}

/**
 * Sets up nge-doc with safe, setup-agnostic steps: a `public/docs` skeleton,
 * the docs builder target when `angular.json` exists, `provideNgeDoc()` when
 * the official standalone utility can do it, and printed instructions for the
 * one edit never attempted automatically (the route).
 */
export function ngAdd(options: Schema): Rule {
  return (tree: Tree, context: SchematicContext) => {
    const project = resolveProject(tree, options.project)
    if (!project) {
      context.logger.warn(
        'No angular.json found: scaffolding public/docs only. ' +
          'Register the @cisstech/nge:docs target and provideNgeDoc() yourself (printed below).'
      )
    }
    return chain([
      scaffoldDocs(project?.publicDir ?? 'public'),
      project ? addDocsTarget(project) : noop(),
      project ? addRootProviders(project.name) : noop(),
      printNextSteps(project),
    ])
  }
}

function resolveProject(tree: Tree, name?: string): TargetProject | null {
  const raw = tree.read('/angular.json')
  if (!raw) {
    return null
  }
  const workspace = JSON.parse(raw.toString())
  const projects = workspace.projects ?? {}
  const projectName =
    name && projects[name] ? name : Object.keys(projects).find((key) => projects[key].projectType === 'application')
  if (!projectName) {
    return null
  }
  const project = projects[projectName]
  const targetsKey = project.architect ? 'architect' : 'targets'
  return { name: projectName, publicDir: publicDirOf(project), targetsKey }
}

/** The app assets dir: the first non-glob `input` of the build assets, or `<root>/public`. */
function publicDirOf(project: { root?: string; architect?: unknown; targets?: unknown }): string {
  const targets = (project.architect ?? project.targets ?? {}) as Record<string, { options?: { assets?: unknown[] } }>
  for (const entry of targets['build']?.options?.assets ?? []) {
    if (typeof entry === 'object' && entry !== null && 'input' in entry) {
      return String((entry as { input: unknown }).input)
    }
  }
  return [project.root, 'public'].filter(Boolean).join('/')
}

function scaffoldDocs(publicDir: string): Rule {
  return (tree: Tree) => {
    const write = (path: string, content: string) => {
      const full = `/${publicDir}/docs/${path}`.replace(/\/+/g, '/')
      if (!tree.exists(full)) {
        tree.create(full, content)
      }
    }
    write(
      'index.md',
      `---
title: Introduction
description: What this documentation covers.
---

# Welcome

This site is generated by [nge-doc](https://cisstech.github.io/nge/docs/nge-doc):
every markdown file under this folder becomes a page, folders become sections,
and \`_meta.json\` controls titles and order.
`
    )
    write(
      'getting-started.md',
      `---
description: Set up the project locally.
---

# Getting started

Edit this page, add more markdown files, then rebuild the manifest:

\`\`\`bash
ng run <your-app>:docs
\`\`\`
`
    )
    write('_meta.json', `${JSON.stringify({ 'getting-started': { title: 'Getting started' } }, null, 2)}\n`)
    return tree
  }
}

function addDocsTarget(project: TargetProject): Rule {
  return (tree: Tree) => {
    const workspace = JSON.parse(tree.read('/angular.json')!.toString())
    const definition = workspace.projects[project.name]
    const targets = (definition[project.targetsKey] ??= {})
    if (!targets['docs']) {
      targets['docs'] = {
        builder: '@cisstech/nge:docs',
        options: { publicDir: project.publicDir, root: '/docs', name: project.name },
      }
      tree.overwrite('/angular.json', `${JSON.stringify(workspace, null, 2)}\n`)
    }
    return tree
  }
}

/**
 * Best-effort: the official standalone utility handles `app.config.ts` and
 * inline `bootstrapApplication` setups. Anything else (NgModule apps, missing
 * @schematics/angular) falls back to the printed instructions.
 */
function addRootProviders(projectName: string): Rule {
  return (tree: Tree, context: SchematicContext) => {
    try {
      // Resolved at run time inside the CLI, where @schematics/angular is present.
      // eslint-disable-next-line @typescript-eslint/no-require-imports
      const { addRootProvider } = require('@schematics/angular/utility') as {
        addRootProvider: (
          project: string,
          callback: (helpers: {
            code: (strings: TemplateStringsArray, ...values: unknown[]) => unknown
            external: (name: string, module: string) => unknown
          }) => unknown
        ) => Rule
      }
      return addRootProvider(projectName, ({ code, external }) => {
        return code`${external('provideNgeDoc', '@cisstech/nge/doc')}()`
      })
    } catch {
      context.logger.warn('Could not add provideNgeDoc() automatically; add it to your providers (printed below).')
      return tree
    }
  }
}

function printNextSteps(project: TargetProject | null): Rule {
  return (tree: Tree, context: SchematicContext) => {
    const app = project?.name ?? '<your-app>'
    context.logger.info(`
nge-doc is ready. Next steps:

1. Route the documentation (src/app/app.routes.ts):

   import { docsFromManifest } from '@cisstech/nge/doc'

   {
     path: 'docs',
     loadChildren: () => import('@cisstech/nge/doc').then((m) => m.NGE_DOC_ROUTES),
     data: docsFromManifest('docs/nge-doc.json'),
   }

2. Compile the manifest (re-run after adding pages): ng run ${app}:docs

3. Optional, static generation (SSG): see provideNgeDocSsr() and
   ngeDocPrerenderRoutes() from @cisstech/nge/doc/ssr.

Guide: https://cisstech.github.io/nge/docs/nge-doc
`)
    return tree
  }
}
