export * from './src/icongr.pipe'
export * from './src/isobject.pipe'
export * from './src/isstring.pipe'
export * from './src/istemplate.pipe'
export * from './src/length.pipe'
export * from './src/safe.pipe'
