export * from './src/file-icon.pipe';
export * from './src/icon-codicon/icon-codicon.component';
export * from './src/icon-fa/icon-fa.component';
export * from './src/icon-file/icon-file.component';
export * from './src/icon-img/icon-img.component';
export * from './src/icon.component';
export * from './src/icon.module';
export * from './src/icon.pipe';
export * from './src/icons';
