name: Publish Gh Pages

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: 22

jobs:
  prepare:
      name: Prepare
      runs-on: ubuntu-latest
      steps:
        - uses: DerYeger/yarn-setup-action@master
          with:
            node-version: ${{ env.NODE_VERSION }}

  publish:
    runs-on: ubuntu-latest
    needs: prepare
    permissions:
      contents: write  # Write access to repository content
      pages: write  # Write access to publish pages
    steps:
      - uses: DerYeger/yarn-setup-action@master
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Publish to gh-pages
        if: success()
        run:  yarn publish:demo
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAGE_TOKEN }}
